"""Misc parity cases (captured oracles from GNU coreutils 9.4 / bash 5.2).

Each entry is a shell script run under both unish and the oracle shell;
stdout and the exit code must match, and so must the resulting files in
the (fresh) working directory. An entry may be a (script, xfail_reason)
pair when the delta is known cosmetic.
"""

CASES = [

    "basename ''; echo rc=$?",
    'basename /a/b/c c; basename c c',
    ("basename /; basename //; basename '///'", "old-oracle"),
    "basename a/b/; basename 'a/b///'",
    'basename file.txt .txt; basename a.tar.gz .tar.gz',
    "dirname ''; echo rc=$?",
    ("dirname '///'; dirname //", "old-oracle"),
    "dirname 'a/b///'; dirname 'a/b/'",
    "dirname './a/b'; dirname './'; dirname '.'",
    'dirname /a/b/c; dirname a; dirname /',
    'touch f; find . -nosuchpred 2>&1; echo rc=$?',
    'touch f; find . -name f -nosuchpred 2>&1; echo rc=$?',
    ('touch f; find . -perm notamode 2>&1; echo rc=$?', "oracle-wording"),
    "touch a.txt b.md; find . -name '*.txt' | sort",
    'mkdir -p x/y; touch x/y/f g; find . -name x -prune -o -print | sort',
    'mkdir d; echo x > d/f; tar -cf a.tar d; rm -rf d; tar -xf a.tar -C nosuch 2>&1; echo rc=$?; ls',
    'mkdir d; echo x > d/f; tar -cf a.tar d; rm -rf d; mkdir out; tar -xf a.tar -C out; cat out/d/f',
    "printf 'x\\n' | xargs false; echo rc=$?",
    ("printf 'x\\n' | xargs nosuchcmd123 2>&1; echo rc=$?", "oracle-wording"),
    "printf 'a\\nb\\n' | xargs -n2 echo",
    "touch -d '2020-01-02 03:04:05' f; date -r f '+%Y-%m-%d %H:%M:%S' 2>&1",
    "printf 'a::b\\n' | cut -d:: -f2 2>&1; echo rc=$?",
    ("printf 'abc\\n' | cut -c1 -f1 2>&1; echo rc=$?", "old-oracle"),
    "printf 'a:b:c\\n' | cut -d: -f2",
    "printf 'abc\\n' | cut -c2-3",
    "printf 'cba\\n' | tr 'z-a' 'a-z' 2>&1; echo rc=$?",
    "printf 'cba\\n' | tr 'a-z' 'A-Z'",
    "printf 'a\\n' | grep -H a",
    ("printf 'a\\x00b\\n' | grep b 2>&1; echo rc=$?", "old-oracle"),
    "printf 'a\\x00b\\n' | grep -a b 2>&1; echo rc=$?",
    "printf 'abc\\n' | grep b",
    '[ -e /dev/null ] && echo yes || echo no',
    '[ -c /dev/null ] && echo chr || echo nochr',
    '[ -s /dev/null ] && echo sz || echo nosz',
    '[ -f /dev/null ] && echo f || echo nf',
    'touch f; [ -e f ] && echo e; [ -f f ] && echo f2; [ ! -d f ] && echo nd',
    '[ 5 -gt 3 ] && echo gt; [ 5 -eq 5 ] && echo eq; [ abc = abc ] && echo eq2',
    "[ -n x ] && echo nn; [ -z '' ] && echo zz",
    'mkdir d; [ -d d ] && echo dd; [ ! -f d ] && echo nff',
    '[ ! -z x ] && echo bang; [ -n a -a -n b ] && echo and',
    "[ '(' x ')' ] 2>&1; echo rc=$?",
    '[ 1 = 1 ] && echo t; [ 1 = 2 ] || echo f',
    "printf 'hello x\\n' | fold -3",
    "printf 'hello x\\n' | fold -b3",
    "printf 'hello x\\n' | fold -s6",
    "printf 'hello x\\n' | fold -w 4",
    "printf 'hello x\\n' | fold -w4",
    "printf 'a\\nb\\nc\\nd\\n' | sed -n '1,+2p'",
    "printf 'a\\nb\\nc\\nd\\ne\\nf\\n' | sed -n '/a/,~3p'",
    "printf 'a\\nb\\nc\\nd\\n' | sed -n '/a/,+0p'",
    "printf 'a\\nb\\nc\\nd\\n' | sed '1,+1d'",
    'echo x > f; sleep 0.1 2>/dev/null; cp -p f g 2>&1; echo rc=$?; ls',
    'echo x > f; cp f g; cat g',
    "printf 'a\\n' > f; printf 'b\\n' | wc -l f -",
    "printf 'ab\\ncd\\n' | uniq -w0",
    "printf '\\tabc\\n' | wc -L",
]
