"""Printf parity cases (captured oracles from GNU coreutils 9.4 / bash 5.2).

Each entry is a shell script run under both unish and the oracle shell;
stdout and the exit code must match, and so must the resulting files in
the (fresh) working directory. An entry may be a (script, xfail_reason)
pair when the delta is known cosmetic.
"""

CASES = [

    "printf '%d\\n' 42",
    ("printf '%d\\n' -- -42 2>&1; echo rc=$?", "bash builtin prefixes diagnostics with 'bash: line N:'"),
    "printf -- '%d\\n' -42; echo rc=$?",
    "printf '%d\\n' 0x1f",
    "printf '%d\\n' 010",
    ("printf '%d\\n' abc 2>&1; echo rc=$?", "bash builtin prefixes diagnostics with 'bash: line N:'"),
    ("printf '[%d]\\n' 3.7 2>&1; echo rc=$?", "bash builtin prefixes diagnostics with 'bash: line N:'"),
    "printf '%i\\n' 017",
    "printf '%x\\n' 255",
    "printf '%X\\n' 255",
    "printf '%o\\n' 8",
    "printf '%u\\n' 42",
    "printf '[%x][%X]\\n' -1 -1",
    "printf '[%u]\\n' -1",
    "printf '%f\\n' 3.14159",
    "printf '%.2f\\n' 3.14159",
    "printf '%e\\n' 1234.5678",
    "printf '%E\\n' 1234.5678",
    "printf '%g\\n' 0.00001",
    "printf '%.3g\\n' 12345",
    "printf '%g\\n' 123456789",
    "printf '%G\\n' 0.00001",
    "printf '[%s]\\n' 'a b'",
    "printf '[%6s][%-6s]\\n' ab ab",
    "printf '[%.1s]\\n' abc",
    "printf '%c\\n' abc",
    "printf '%b\\n' 'a\\101b'",
    "printf '[%*s]\\n' 5 ab; echo END",
    "printf '[%.*s]\\n' 2 abc",
    "printf '[%05d]\\n' 42",
    "printf '[%+d]\\n' 42",
    "printf '[% d]\\n' 42",
    "printf '[%#x]\\n' 255",
    "printf '[%-5d|]\\n' 42",
    "printf '[%05d]\\n' -42",
    'printf \'a\\tb\\nc\\\\d\\"e\\x41\\102\\e[0m\' | od -An -tx1',
    "printf 'a\\cb' | od -An -tx1",
    "printf '%s-%s\\n' a b c d",
    "printf '%s %s\\n' a",
    "printf '100%%\\n'",
    "printf '[%20d]\\n' 1",
    "printf '[%.3d]\\n' 42",
    "printf '\\x4' | od -An -tx1",
    "printf '%d\\n' 9223372036854775807",
    ("printf '%d\\n' 9223372036854775808 2>&1; echo rc=$?", "bash builtin prefixes diagnostics with 'bash: line N:'"),
    "printf '<%s>' a b c; echo",
    "v=5; printf '%d\\n' $v",
    ("printf '%a\\n' 1.5 2>&1; echo rc=$?", "bash builtin %a hex-float normalization varies by build (0xcp-3 vs 0x1.8p+0), same value"),
    "printf '%f\\n' nan 2>&1; echo rc=$?",
    ("printf '%f\\n' inf 2>&1; echo rc=$?", "old-oracle"),
    "printf 'x%dy\\n' 1 2 3",
    "printf '%5.2f|%-8s|\\n' 3.14159 hi",
    "printf '' ; echo rc=$?",
    'printf; echo rc=$?',
    "printf 'no args %d\\n'; echo rc=$?",
    ("printf '\\u00e9|\\U0001F600\\n' | od -An -tx1", "old-oracle"),
    "printf '\\u41\\n' | od -An -tx1",
    "printf '\\e[31mRED\\e[0m\\n' | od -An -tx1 | tr -s ' '",
    'printf \'a\\"b\\n\' | od -An -tx1',
    "printf '%i %i\\n' 08 0x10",
    "printf '%d %d\\n' ' 42' '-42'",
    "printf '%5c|\\n' ab",
    "printf '%-5c|\\n' ab",
    "printf '%*d %*d\\n' 4 7 6 8",
    "printf '%s=%d%%\\n' load 90",
    "printf '%q\\n' abc 2>&1; echo rc=$?",
    "printf '%%s\\n' foo",
    "printf '%d\\n' +42",
    "printf '%x\\n' 0x10",
    "printf '[%08.3f]\\n' 2.5",
]
