"""Sed parity cases (captured oracles from GNU coreutils 9.4 / bash 5.2).

Each entry is a shell script run under both unish and the oracle shell;
stdout and the exit code must match, and so must the resulting files in
the (fresh) working directory. An entry may be a (script, xfail_reason)
pair when the delta is known cosmetic.
"""

CASES = [

    "printf 'aaa\\n' | sed 's/a/X/g'",
    "printf 'aaa\\n' | sed 's/a/X/'",
    "printf 'aaaa\\n' | sed 's/a/X/2'",
    "printf 'aaaa\\n' | sed 's/a/X/2g'",
    "printf 'a\\nb\\nc\\n' | sed '$d'",
    "printf 'a\\nb\\nc\\n' | sed '2d'",
    "printf 'a\\nb\\nc\\nd\\n' | sed '2,3d'",
    "printf 'a\\nb\\nc\\nb\\nd\\n' | sed '/b/,/c/d'",
    "printf 'x\\ny\\nx\\ny\\nx\\n' | sed '/x/,/y/d'",
    "printf 'a\\nb\\n' | sed '0,/a/s/a/Z/'",
    "printf '1\\n2\\n3\\n4\\n5\\n' | sed '1~2d'",
    "printf '1\\n2\\n3\\n4\\n5\\n' | sed '0~2d'",
    "printf 'a\\nb\\n' | sed -n 'h;${x;p}'",
    "printf 'a\\nb\\n' | sed -n 'H;${x;s/\\n//;p}'",
    "printf 'a\\nb\\n' | sed '1h;2x;p'",
    "printf 'a\\nb\\nc\\n' | sed 'N;s/\\n/-/'",
    "printf 'a\\nb\\nc\\n' | sed 'N;s/^/> /'",
    "printf 'a1\\nb1\\na2\\n' | sed -n '/a/{N;P;D}'",
    "printf 'aaa\\n' | sed ':a;s/a//;ta'",
    "printf 'abc\\n' | sed 'y/abc/xyz/'",
    "printf 'a\\nb\\n' | sed '/a/a TEXT'",
    "printf 'a\\n' | sed '/a/a\\   indented'",
    "printf 'a\\nb\\n' | sed '/b/i TEXT'",
    "printf 'a\\nb\\nc\\n' | sed '2c TEXT'",
    "printf 'a\\nb\\nc\\nd\\n' | sed '2,3c TEXT'",
    "printf 'a\\nb\\nc\\n' | sed '/a/,/zz/c TEXT'",
    "printf 'a\\nb\\nc\\n' | sed '/a/,/b/c TEXT'",
    "printf 'a\\nb\\n' | sed '='",
    "printf 'a\\nb\\n' | sed -n 'p'",
    "printf 'abc\\n' | sed -E 's/(a)(b)/\\2\\1/'",
    "printf 'abc\\n' | sed 's/\\(a\\)\\(b\\)/\\2\\1/'",
    "printf 'foo\\n' | sed 's/o/&&/'",
    "printf 'ab\\n' | sed 's/a/\\n/' | cat -A",
    "printf 'a&b\\n' | sed 's/&/X/'",
    "printf 'ab\\n' | sed 's/b/$/'",
    "printf 'a/b\\n' | sed 's@a@X@'",
    "printf 'abc\\n' | sed 's//X/' 2>&1; echo rc=$?",
    "printf 'abc\\n' | sed 's/b//'",
    "printf 'ABC\\n' | sed 's/abc/X/I'",
    "printf 'a\\nb\\n' | sed -n 'w out'; echo '--'; cat out",
    "printf 'ab\\n' | sed -n 's/a/X/w out2'; cat out2",
    "printf 'a\\nb\\nc\\n' | sed '2q'; echo rc=$?",
    "printf 'a\\nb\\n' | sed '1q3'; echo rc=$?",
    "printf 'a\\nb\\n' | sed '1Q3'; echo rc=$?",
    "printf 'a\\n' | sed -n '{=;p}'",
    "printf 'abc\\n' | sed -e 's/a/X/' -e 's/c/Y/'",
    "printf 'ab' | sed 's/a/X/'",
    "printf 'ab\\ncd' | sed 'N;s/\\n/-/'",
    "printf 'a\\nb' | sed '$s/b/Z/'",
    "printf 'a\\n' > f; sed -i 's/a/X/' f; cat f",
    "printf '\\n\\n' | sed 's/^$/E/'",
    "printf 'abc 123\\n' | sed 's/[[:digit:]]\\+/N/'",
    "printf 'abc\\n' | sed 's/a*/X/'",
    "printf 'a\\n' | sed '10d'",
    "printf 'aaa\\n' | sed ':x;s/a/b/;tx'",
    "printf 'a\\nb\\n' | sed 'G' | cat -A",
    "printf 'abc\\n' | sed 's/x*/-/g'",
    "printf 'a-b\\n' | sed 's/-/[&]/'",
    "printf 'a\\nb\\nc\\n' | sed '2,$d'",
    "printf 'a\\n' | sed '/a/{s//Y/}'",
    "printf 'aab\\n' | sed -e 's/a/Z/' -e 's//Y/'",
    ("printf 'a\\n' | sed 's/a/\\1/' 2>&1; echo rc=$?", 'sed error position wording (char N)'),
    ("printf 'a\\n' | sed 's/\\(a\\)/\\2/' 2>&1; echo rc=$?", 'sed error position wording (char N)'),
    "printf 'a\\n' | sed 'n' | cat -A",
    "printf 'a\\n' | sed '1Q' | cat -A; echo rc=$?",
    "printf 'a\\n' | sed 'N;s/a/X/'",
    "printf 'a\\nb\\nc\\nd\\n' | sed -n '/a/{N;P;D}'",
    "printf 'a\\nb\\nc\\n' | sed '$!{N};s/\\n/-/'",
    ("printf 'a\\n' | sed 's/a/X/; //' 2>&1; echo rc=$?", 'sed error position wording (char N)'),
    ("printf 'a\\n' | sed 's/a' 2>&1; echo rc=$?", 'sed error position wording (char N)'),
    "printf 'a\\nb\\n' | sed '1{h;d};G'",
    "printf 'x\\n' | sed 's/x/\\U&/'",
    "printf 'x\\n' | sed 's/x/\\LX/'",
    "printf 'a\\tb\\n' | sed 's/\\t/,/'",
    "printf 'abc\\n' | sed 's/b/\\n\\n/'",
    "printf 'a\\nb\\n' | sed -e '/a/d' -e '/b/d'",
    "printf 'hello\\n' | sed 's/\\(l\\)\\(o\\)/\\2\\1/g'",
    "printf 'a\\n' | sed '$d'",
    "printf 'a\\nb\\nc\\n' | sed -n '/a/,/b/p'",
    "printf 'a\\nb\\nc\\nd\\n' | sed -n '/b/,/c/{p}'",
    "printf 'aaa\\n' | sed 's/a/b/3'",
    "printf 'ab\\n' | sed 's@\\(a\\)@<&>@'",
    "printf 'a\\nA\\n' | sed 's/\\(a\\)/X/I'",
    "printf 'a\\nb\\n' | sed 'N;P;N;D'",
    "printf 'a\\nb\\nc\\n' | sed -n '$='",
    "printf 'a\\nb\\n' | sed '2!d'",
]
