"""Sort parity cases (captured oracles from GNU coreutils 9.4 / bash 5.2).

Each entry is a shell script run under both unish and the oracle shell;
stdout and the exit code must match, and so must the resulting files in
the (fresh) working directory. An entry may be a (script, xfail_reason)
pair when the delta is known cosmetic.
"""

CASES = [

    "printf 'b\\na\\nc\\n' | sort",
    "printf 'b\\na\\nc\\n' | sort -r",
    "printf '10\\n9\\n-2\\n0\\n1e3\\n' | sort -n",
    "printf '1.5\\n1.10\\n-0.5\\n0\\n' | sort -n",
    "printf '99999999999999999999\\n1\\n-99999999999999999999\\n' | sort -n",
    "printf 'b\\na\\nb\\nA\\n' | sort -u",
    "printf 'b\\nA\\na\\nB\\n' | sort -fu",
    "printf 'b\\nA\\na\\nB\\n' | sort -f",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -s -k2",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -k2",
    "printf 'z:10\\na:2\\nb:02\\n' | sort -t: -k2 -n",
    "printf 'a b c\\na a c\\na b a\\n' | sort -k2,2",
    "printf 'b x\\na z\\n' | sort -k2",
    "printf 'a 2\\na 1\\nb 1\\nb 2\\n' | sort -k1,1 -k2,2n",
    "printf 'v1.10\\nv1.9\\nv1.2\\nv1.2.1\\n' | sort -V",
    "printf 'b\\0a\\0c\\0' | sort -z | tr '\\0' '\\n'",
    "printf '' | sort",
    "printf 'b\\na' | sort",
    "printf 'a' | sort",
    "printf 'b\\n\\n a\\n\\n' | sort",
    "printf 'a\\nb\\n' | sort -c; echo rc=$?",
    "printf 'b\\na\\n' | sort -c; echo rc=$?",
    "printf 'a\\na\\n' | sort -cu; echo rc=$?",
    "printf 'b\\na\\n' > f; sort -o f f; cat f",
    "printf 'a.b\\nab\\n' | sort -d 2>&1; echo rc=$?",
    "printf 'x  2\\nx   1\\n' | sort -b -k2",
    "printf 'a 2\\nA 1\\n' | sort -k2,2n -k1,1r",
    "printf 'a\\tb\\na\\tz\\n' | sort",
    "printf 'a\\n' | sort -k5",
    ("printf 'a::1\\nb::2\\n' | sort -t:: -k2 2>&1; echo rc=$?", "old-oracle"),
    "printf ' y,2\\nz\\n1\\n2\\n' | sort -k1,1",
    "printf 'a  2\\na   1\\n' | sort -k2,2",
    "printf 'a 2\\na  2\\n' | sort -k2,2",
    "printf 'a  2\\na   1\\n' | sort -b -k2,2",
    "printf 'a 9\\na 10\\nb 2\\n' | sort -k2",
    "printf 'a bb\\na bc\\n' | sort -k2.2",
    "printf 'a xyz\\na xzz\\n' | sort -k1.3,1.4",
    "printf 'a xy\\na x\\n' | sort -k1.3,1.4",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -r -k2",
    "printf 'b\\na\\n' | sort -r",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -k2,2r",
    "printf '1e3\\n9\\n10\\n 5\\nx\\n0x10\\n.5\\n-3\\n+4\\n5abc\\n' | sort -n",
    "printf 'a:1\\nb:01\\n' | sort -t: -k2,2",
    "printf 'a\\nb:1\\n' | sort -t: -k2,2",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -k2,2 -k1,1",
    "printf 'a 2\\na 1\\nA 3\\n' | sort -k2,2r -k1,1",
    "printf 'A x\\na 1\\n' | sort -f -k2",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -u -k2",
    "printf 'ab\\nac\\n' | sort -k1.2,1.1",
    "printf 'a 2\\na 1\\n' | sort -k2,2.1",
    "printf 'a b c\\na b a\\na a c\\n' | sort -k3,3 -k1,1",
    "printf 'a 10\\nb 2\\n' | sort -k2n",
    "printf '  b\\n a\\n' | sort",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -s -k2",
    "printf 'a::1\\na:2\\n' | sort -t: -k2,2",
    "printf 'b 02\\na 2\\n' | sort -k2,2n",
    "printf 'a  2\\na   1\\n' | sort -rb -k2,2",
    "printf ' z\\na\\n' | sort -k1,1",
    "printf 'a  x\\na y\\n' | sort -k2,2",
    "printf 'a x \\na y\\n' | sort -b -k2",
    "printf 'a x \\na y\\n' | sort -k2",
    "printf 'a b x\\na b  y\\n' | sort -k3,3",
    "printf -- '-.5\\n-\\n.\\n-0\\n+2\\n' | sort -n",
    "printf '9007199254740993\\n9007199254740992\\n' | sort -n",
    "printf ' 5\\n4\\n' | sort -n",
    "printf ' -5\\n- 5\\n' | sort -n",
    "printf 'a B\\na b\\na A\\n' | sort -fk2",
    "printf 'A\\na\\n' | sort -rf",
    "printf 'a 1\\nb 1\\nc 2\\n' | sort -u -k2",
    "printf 'ab\\na\\n' | sort -k1.1,1.1",
    "printf 'a x\\na y \\n' | sort -b -k2,2",
    "printf 'a x \\na x\\n' | sort -bu -k2",
    "printf 'a x \\na x\\n' | sort -u -k2",
    "printf 'a x \\na xy\\n' | sort -k2",
    "printf ' b\\na\\n' | sort -b",
    "printf 'a xy\\na x\\n' | sort -u -k1.3,1.4",
    "printf 'b x\\na xyz\\n' | sort -k1.3",
    "printf 'b x\\na xyz\\n' | sort -u -k1.3",
    "printf 'ab\\na\\n' | sort -k3.2",
    "printf 'a\\na\\n' | sort -cu",
    "printf 'b\\na\\n' | sort -c",
    "printf 'ab\\nac\\n' | sort -k2,1",
    "printf -- '- 5\\n0\\n-5\\n' | sort -n",
    "printf '10000000000000000001\\n9999999999999999999\\n' | sort -n",
    "printf 'a xy \\na xy\\n' | sort -bu -k2,2",
    "printf 'a y \\na y\\n' | sort -u -k2,2",
    "printf 'a y \\na y z\\n' | sort -k2,2",
    "printf 'a y \\na y z\\n' | sort -u -k2,2",
    "printf '02\\n2\\n2.0\\n' | sort -n",
    "printf 'a:1\\nb:2:3\\n' | sort -t: -k3,3",
    "printf 'a x1\\na y2\\n' | sort -k2.2",
    "printf 'a x1\\na y2\\n' | sort -b -k2.2",
    "printf 'a 123\\na 124\\n' | sort -u -k2.2,2.3",
    "printf 'a 123\\na 124\\n' | sort -bu -k2.2,2.3",
    "printf 'a xy\\na x\\n' | sort -k2.2,2.3",
    "printf 'a y\\na b\\n' | sort -k1.2",
    "printf 'x\\t2\\nx\\t10\\n' | sort -t$'\\t' -k2n",
    "printf 'A 2\\na 1\\n' | sort -k2,2n -k1,1r",
    "printf 'a.b\\nab\\n' | sort -d",
    "printf 'a!b\\nab\\n' | sort -d",
    "printf 'a\\tb\\nab\\n' | sort -i",
    "printf '1e3\\n9\\n10\\n' | sort -g",
    "printf '1K\\n2M\\n512\\n1G\\n' | sort -h",
    "printf 'Mar\\nJan\\nFeb\\n' | sort -M",
    "printf 'Mar 2020\\nJan 2021\\nFeb 2020\\n' | sort -k2,2M",
    "printf 'a 10\\nb 2\\n' | sort -k2g",
    "printf 'a 1K\\nb 512\\n' | sort -k2h",
    "printf 'b\\nA\\na\\nB\\n' | sort -fd",
    "printf -- '-.5\\n-\\n.\\n-0\\n+2\\n' | sort -n",
    "printf -- '- 5\\n0\\n-5\\n' | sort -n",
    "printf '1e3\\n9\\n10\\n 5\\nx\\n0x10\\n.5\\n-3\\n+4\\n5abc\\n' | sort -n",
    "printf '9007199254740993.5\\n9007199254740993.1\\n' | sort -n",
    "printf 'x 1\\nb 1\\na 1\\n' | sort -k2nr",
    "printf 'a\\t1\\nb\\t2\\n' | sort -t$'\\t' -k2n",
]
